# Site

title: Python for Geospatial Modeling
subtitle: Temperature Regression
handouts:
  - data/README.md
  - data/lst_mean_month1_rescaled.tif
  - data/lst_mean_month7_rescaled.tif
  - data/ghcn_or_tmax_covariates_06262012_OR83M.shp
  - data/ghcn_or_tmax_covariates_06262012_OR83M.shx
  - data/ghcn_or_tmax_covariates_06262012_OR83M.prj
  - data/ghcn_or_tmax_covariates_06262012_OR83M.dbf
  - data/ghcn_or_tmax_covariates_06262012_OR83M.txt
  - data/ghcn_or_tmax_covariates_06262012_OR83M.sbx
  - data/ghcn_or_tmax_covariates_06262012_OR83M.sbn
##ARGS 11
tag: v0.0
lesson: 6
instructor: Benoit Parmentier
authors:
  - Benoit Parmentier

# Slides

slide_sorter:

#####################################
# Only modify content above or risk #
# merge conflicts with upstream.    #
#####################################

# Style

styleurl: https://cdn.rawgit.com/sesync-ci/lesson-style/v2.0/docs
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.5.0

# Jekyll

markdown: kramdown
collections:
  - slides
